"""Initial KB schema: kb_source, kb_assertion, kb_review, kb_release.

Mirrors docs/design.md section 6.1 (with the two deviations recorded in
ADR-006: deterministic ids computed in code, and nullable taxon_key for
claims not yet anchored to the backbone).

On PostgreSQL this migration also enables the pg_trgm extension and builds
a trigram index on kb_assertion.name_normalized — that index is what makes
the fuzzy candidate-recall stage of the matching engine (design section 7,
stage 3) fast. On other databases (SQLite in tests) it is skipped.

Revision ID: 8b165f3e1753
Revises:
Create Date: 2026-09-18
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "8b165f3e1753"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kb_release",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("zenodo_doi", sa.Text(), nullable=True),
        sa.Column("assertion_count", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "kb_source",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("license", sa.Text(), nullable=False),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("license_verified_on", sa.Text(), nullable=True),
        sa.Column("default_confidence", sa.Float(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "kb_assertion",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vernacular_name", sa.Text(), nullable=False),
        sa.Column("name_normalized", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), nullable=False),
        sa.Column("script", sa.Text(), nullable=False),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column("region_detail", sa.Text(), nullable=True),
        sa.Column("scientific_name", sa.Text(), nullable=False),
        sa.Column("taxon_key", sa.BigInteger(), nullable=True),
        sa.Column("backbone_version", sa.Text(), nullable=True),
        sa.Column("backbone_match_type", sa.Text(), nullable=True),
        sa.Column("backbone_confidence", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_record_id", sa.Text(), nullable=True),
        sa.Column("license", sa.Text(), nullable=False),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("verification_status", sa.Text(), nullable=False),
        sa.Column("contributor", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["kb_source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["kb_assertion.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kb_assertion_language"), "kb_assertion", ["language"], unique=False)
    op.create_index(
        "ix_kb_assertion_lookup", "kb_assertion", ["language", "name_normalized"], unique=False
    )
    op.create_index(
        op.f("ix_kb_assertion_name_normalized"), "kb_assertion", ["name_normalized"], unique=False
    )
    op.create_index(op.f("ix_kb_assertion_taxon_key"), "kb_assertion", ["taxon_key"], unique=False)
    op.create_index(
        op.f("ix_kb_assertion_verification_status"),
        "kb_assertion",
        ["verification_status"],
        unique=False,
    )
    op.create_table(
        "kb_review",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assertion_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assertion_id"],
            ["kb_assertion.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kb_review_assertion_id"), "kb_review", ["assertion_id"], unique=False)

    # Postgres-only: trigram index for fuzzy name recall (design section 7).
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        op.execute(
            "CREATE INDEX ix_kb_assertion_name_trgm ON kb_assertion "
            "USING gin (name_normalized gin_trgm_ops)"
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.drop_index("ix_kb_assertion_name_trgm", table_name="kb_assertion")
    op.drop_index(op.f("ix_kb_review_assertion_id"), table_name="kb_review")
    op.drop_table("kb_review")
    op.drop_index(op.f("ix_kb_assertion_verification_status"), table_name="kb_assertion")
    op.drop_index(op.f("ix_kb_assertion_taxon_key"), table_name="kb_assertion")
    op.drop_index(op.f("ix_kb_assertion_name_normalized"), table_name="kb_assertion")
    op.drop_index("ix_kb_assertion_lookup", table_name="kb_assertion")
    op.drop_index(op.f("ix_kb_assertion_language"), table_name="kb_assertion")
    op.drop_table("kb_assertion")
    op.drop_table("kb_source")
    op.drop_table("kb_release")
    # ### end Alembic commands ###
